name: PriENE
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - annotated-types=0.7.0
  - anyio=4.9.0
  - aom=3.9.1
  - appdirs=1.4.4
  - arrow=1.3.0
  - asttokens=3.0.0
  - attr=2.5.1
  - attrs=25.3.0
  - binaryornot=0.4.4
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cachetools=5.5.2
  - cairo=1.18.4
  - certifi=2025.4.26
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.2
  - click=8.2.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.2
  - cookiecutter=2.6.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.14
  - decorator=5.2.1
  - docker-pycreds=0.4.0
  - double-conversion=3.3.1
  - eval_type_backport=0.2.2
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.0
  - filelock=3.18.0
  - fluidsynth=2.3.7
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.0
  - freetype=2.13.3
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - gitdb=4.0.12
  - gitpython=3.1.44
  - graphite2=1.3.13
  - h11=0.16.0
  - h2=4.2.0
  - harfbuzz=11.2.1
  - hpack=4.1.0
  - humanize=4.12.3
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=9.2.0
  - ipython_pygments_lexers=1.1.1
  - ipyvue=1.11.2
  - ipyvuetify=1.11.0
  - ipywidgets=8.1.7
  - jack=1.9.22
  - jedi=0.19.2
  - jinja2=3.1.6
  - jsonschema=4.23.0
  - jsonschema-specifications=2025.4.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.15
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-aarch64=2.43
  - lerc=4.0.0
  - libabseil=20250127.1
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.75
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.4
  - libclang13=20.1.4
  - libcups=2.3.3
  - libdb=6.2.32
  - libdeflate=1.24
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.5
  - liblzma=5.8.1
  - libmad=0.15.1b
  - libnsl=2.0.1
  - libntlm=1.4
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopengl=1.7.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.5
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.49.2
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.4
  - libtiff=4.7.0
  - libudev1=257.4
  - libunwind=1.6.2
  - liburing=2.9
  - libusb=1.0.28
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.9.2
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - markdown=3.8
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mesa=2.3.0
  - mesa-viz-tornado=0.1.3
  - mpg123=1.32.9
  - munkres=1.1.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.5.0
  - opusfile=0.12
  - packaging=25.0
  - pandas=2.2.3
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1.1
  - pixman=0.46.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - portaudio=19.6.0
  - portmidi=2.0.4
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pydantic=2.11.4
  - pydantic-core=2.33.2
  - pygame=2.6.1
  - pygments=2.19.1
  - pymdown-extensions=10.15
  - pyparsing=3.2.3
  - pyside6=6.9.0
  - pysocks=1.7.1
  - python=3.11.12
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-slugify=8.0.4
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - qt6-main=6.9.0
  - rav1e=0.7.1
  - reacton=1.9.1
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - rich=14.0.0
  - rich-click=1.8.8
  - rpds-py=0.25.0
  - scipy=1.15.2
  - sdl2=2.32.54
  - sdl2_image=2.8.2
  - sdl2_mixer=2.6.3
  - sdl2_ttf=2.24.0
  - sdl3=3.2.12
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - sentry-sdk=2.28.0
  - setproctitle=1.3.6
  - setuptools=80.1.0
  - six=1.17.0
  - smmap=5.0.2
  - sniffio=1.3.1
  - solara=1.45.0
  - solara-server=1.45.0
  - solara-ui=1.45.0
  - stack_data=0.6.3
  - starlette=0.46.2
  - statsmodels=0.14.4
  - svt-av1=3.0.2
  - text-unidecode=1.3
  - tk=8.6.13
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing=3.10.0.0
  - typing-extensions=4.13.2
  - typing-inspection=0.4.0
  - typing_extensions=4.13.2
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.4.0
  - uvicorn=0.34.2
  - wandb=0.19.11
  - watchdog=6.0.0
  - watchfiles=1.0.5
  - wayland=1.23.1
  - wcwidth=0.2.13
  - websockets=15.0.1
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.2.2
      - astunparse==1.6.3
      - flatbuffers==25.2.10
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - h5py==3.13.0
      - keras==3.9.2
      - libclang==18.1.1
      - ml-dtypes==0.3.2
      - namex==0.0.9
      - numpy==1.26.4
      - opt-einsum==3.4.0
      - optree==0.15.0
      - protobuf==4.25.7
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
prefix: /home/b5v/jwoodgate.b5v/miniforge3/envs/PriENE
