name: nenv
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - absl-py=1.4.0=py311h06a4308_0
  - aiohttp=3.9.3=py311h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.2=py311h06a4308_0
  - atk-1.0=2.36.0=ha1a6a79_0
  - attrs=23.1.0=py311h06a4308_0
  - blas=1.0=mkl
  - blinker=1.6.2=py311h06a4308_0
  - boost-cpp=1.73.0=h7f8727e_12
  - brotli-python=1.0.9=py311h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - cachetools=5.3.3=py311h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2024.2.2=py311h06a4308_0
  - cffi=1.16.0=py311h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py311h06a4308_0
  - cryptography=41.0.3=py311h130f0dd_0
  - expat=2.6.2=h6a678d5_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.4.0=py311h5eee18b_0
  - gast=0.4.0=pyhd3eb1b0_0
  - gdk-pixbuf=2.42.10=h5eee18b_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gobject-introspection=1.78.1=py311hd56c82f_0
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.5.2=py311h06a4308_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.14=h295c915_1
  - grpc-cpp=1.48.2=h5bf31a4_0
  - grpcio=1.48.2=py311h5bf31a4_0
  - gtk2=2.24.33=h73c1081_2
  - gts=0.7.6=hb67d8dd_3
  - harfbuzz=4.3.0=hf52aaf7_1
  - hdf5=1.12.1=h70be1eb_2
  - icu=58.2=he6710b0_3
  - idna=3.4=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_1
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - krb5=1.20.1=h568e23c_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libboost=1.73.0=h28710b8_12
  - libcurl=8.2.1=h91b91d3_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgd=2.3.3=h695aa2c_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libnghttp2=1.52.0=ha637b67_1
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - librsvg=2.54.4=h36cc946_3
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libtool=2.4.6=h6a678d5_1009
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.10.4=hcbfbd50_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown=3.4.1=py311h06a4308_0
  - markupsafe=2.1.3=py311h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - multidict=6.0.4=py311h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numpy=1.23.5=py311h08b1b3b_1
  - numpy-base=1.23.5=py311hf175353_1
  - oauthlib=3.2.2=py311h06a4308_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1w=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=23.2=py311h06a4308_0
  - pango=1.50.7=h05da053_0
  - pcre2=10.42=hebb0a14_0
  - pixman=0.40.0=h7f8727e_1
  - poppler=22.12.0=h9614445_3
  - poppler-data=0.4.11=h06a4308_1
  - protobuf=3.20.3=py311h6a678d5_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py311h06a4308_0
  - pyopenssl=23.2.0=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.5=h7a1cb2a_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py311h06a4308_1
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.12.0=py311h08b1b3b_0
  - setuptools=68.2.2=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h6a678d5_1
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow-base=2.12.0=mkl_py311he5f8e37_0
  - tensorflow-estimator=2.12.0=py311h06a4308_0
  - termcolor=2.1.0=py311h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - typing_extensions=4.9.0=py311h06a4308_1
  - urllib3=2.1.0=py311h06a4308_1
  - werkzeug=2.3.8=py311h06a4308_0
  - wheel=0.41.2=py311h06a4308_0
  - wrapt=1.14.1=py311h5eee18b_0
  - xz=5.4.6=h5eee18b_0
  - yarl=1.9.3=py311h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - anyio==4.0.0
      - appdirs==1.4.4
      - arrow==1.3.0
      - asttokens==2.4.1
      - binaryornot==0.4.4
      - chardet==5.2.0
      - cloudpickle==3.0.0
      - comm==0.1.4
      - contourpy==1.1.1
      - cookiecutter==2.4.0
      - cycler==0.12.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - executing==2.0.1
      - fastjsonschema==2.18.1
      - flatbuffers==23.5.26
      - fonttools==4.43.1
      - gitdb==4.0.11
      - gitpython==3.1.42
      - h11==0.14.0
      - h5py==3.11.0
      - humanize==4.8.0
      - ipykernel==6.26.0
      - ipython==8.17.2
      - ipyvue==1.10.1
      - ipyvuetify==1.8.10
      - ipywidgets==8.1.1
      - jax==0.4.19
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.4.0
      - jsonschema==4.19.2
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.5.0
      - jupyter-core==5.5.0
      - jupyterlab-widgets==3.0.9
      - keras==3.3.2
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - markdown-it-py==3.0.0
      - matplotlib==3.8.1
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mesa==2.1.2
      - mesa-viz-tornado==0.1.1
      - ml-dtypes==0.3.1
      - namex==0.0.8
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.2.1
      - optree==0.11.0
      - pandas==2.1.2
      - parso==0.8.3
      - patsy==0.5.3
      - pexpect==4.8.0
      - pillow==10.1.0
      - pip==24.1.2
      - platformdirs==3.11.0
      - prompt-toolkit==3.0.39
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygame==2.5.2
      - pygments==2.16.1
      - pymdown-extensions==10.3.1
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-graphviz==0.20.3
      - python-slugify==8.0.1
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - reacton==1.8.0
      - referencing==0.30.2
      - rich==13.6.0
      - rich-click==1.7.1
      - rpds-py==0.10.6
      - seaborn==0.13.2
      - sentry-sdk==1.42.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sniffio==1.3.0
      - solara==1.22.0
      - stack-data==0.6.3
      - starlette==0.31.1
      - statsmodels==0.14.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.2
      - tensorflow-io-gcs-filesystem==0.36.0
      - text-unidecode==1.3
      - threadpoolctl==3.4.0
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.13.0
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - uvicorn==0.23.2
      - wandb==0.16.4
      - watchdog==3.0.0
      - wcwidth==0.2.9
      - websockets==12.0
      - widgetsnbextension==4.0.9
prefix: /home/yp19484/anaconda3/envs/nenv
